
GET http://localhost:3000/subscribers

###

GET http://localhost:3000/subscribers/608e58134e5a103008f20

###
POST http://localhost:3000/subscribers
Content-Type:application/json

{
    "name": "Amazing Person",
    "subscribedToChannel" : "AbrialWong"
}
